# Build for .NET Core project

trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: GodelTech
      type: github
      endpoint: godeltech
      name: GodelTech/Yaml.Common

stages:
- template: templates/nuget.yml@GodelTech
  parameters:
    sonarCloudOrganizationName: 'godeltech'
    sourceBranch: 'master'
    buildConfiguration: 'Release'
    packDirectory: packages

- stage: Artifacts
  displayName: 'Artifacts'
  dependsOn: Build
  jobs:
    - deployment: Publish
      displayName: 'Publish packages'
      environment: 'Artifacts'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: NuGetCommand@2
              displayName: 'NuGet push'
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
                nuGetFeedType: 'internal'
                publishVstsFeed: '19324bbd-9baf-4407-b86d-3e7f0d145399/1574777e-9941-4b90-baa9-d9938266ac24'

- stage: NuGet
  displayName: 'NuGet'
  dependsOn: Artifacts
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - deployment: Publish
      displayName: 'Publish packages'
      environment: 'NuGet'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: NuGetCommand@2
              displayName: 'NuGet push'
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
                nuGetFeedType: 'external'
                publishFeedCredentials: 'NuGet'
