trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

resources:
  repositories:
    - repository: GodelTech
      type: github
      endpoint: 'godeltech'
      name: 'GodelTech/AzureDevOps.Pipeline.Templates'
      ref: 'refs/tags/latest'

extends:
  template: '.azuredevops/.NET/NuGet.yml@GodelTech'
  parameters:
    dotNetSDKVersions: [ '6.0.x', '7.0.x', '8.0.x' ]
    mutationTestingProjects:
    - displayName: 'GodelTech.Data.EntityFrameworkCore'
      folderPath: '/src/GodelTech.Data.EntityFrameworkCore'
